#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script tự động áp dụng các sửa lỗi vào enhanced_fields_overrides.py
Dựa trên kết quả từ auto_fix_common_errors.py
"""

import json
import re
from typing import Dict, List

try:
    from drugs.drug_database import DRUG_DATABASE
    from drugs.enhanced_fields_overrides import EXTRA_ENHANCED_FIELDS
except ImportError:
    print("❌ Lỗi: Không thể import DRUG_DATABASE")
    exit(1)

def load_auto_fix_suggestions():
    """Đọc file gợi ý sửa lỗi"""
    try:
        with open('auto_fix_suggestions.txt', 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print("❌ Không tìm thấy auto_fix_suggestions.txt")
        print("   Vui lòng chạy auto_fix_common_errors.py trước")
        return None

def get_drug_fixes_from_memory():
    """Lấy các sửa lỗi từ bộ nhớ (sau khi chạy auto_fix)"""
    fixes = {}
    
    # Các thuốc đã được sửa trong auto_fix_common_errors.py
    # Chúng ta cần chạy lại logic sửa để lấy dữ liệu
    from auto_fix_common_errors import (
        fix_guideline_tags_type,
        fix_empty_interactions,
        fix_overdose_management_structure,
        fix_administration_instructions_structure
    )
    
    # Load báo cáo validation
    try:
        with open('drug_validation_report.json', 'r', encoding='utf-8') as f:
            report = json.load(f)
    except FileNotFoundError:
        print("❌ Không tìm thấy drug_validation_report.json")
        return {}
    
    for drug_name in report.get("drugs_with_errors", []):
        drug_data = DRUG_DATABASE.get(drug_name)
        if not drug_data:
            continue
        
        # Tạo bản sao để sửa
        drug_copy = drug_data.copy()
        fixed_fields = {}
        
        # Sửa guideline_tags
        if fix_guideline_tags_type(drug_name, drug_copy):
            if "guideline_tags" in drug_copy:
                fixed_fields["guideline_tags"] = drug_copy["guideline_tags"]
        
        # Sửa interactions
        if fix_empty_interactions(drug_name, drug_copy):
            if "interactions" in drug_copy:
                fixed_fields["interactions"] = drug_copy["interactions"]
        
        # Sửa overdose_management
        if fix_overdose_management_structure(drug_name, drug_copy):
            if "overdose_management" in drug_copy:
                fixed_fields["overdose_management"] = drug_copy["overdose_management"]
        
        # Sửa administration_instructions
        if fix_administration_instructions_structure(drug_name, drug_copy):
            if "administration_instructions" in drug_copy:
                fixed_fields["administration_instructions"] = drug_copy["administration_instructions"]
        
        if fixed_fields:
            fixes[drug_name] = fixed_fields
    
    return fixes

def format_field_value(value):
    """Format giá trị field để ghi vào file Python"""
    if isinstance(value, str):
        # Escape quotes
        value = value.replace('\\', '\\\\').replace("'", "\\'")
        return f"'{value}'"
    elif isinstance(value, list):
        if len(value) == 0:
            return "[]"
        items = []
        for item in value:
            if isinstance(item, str):
                item_str = item.replace('\\', '\\\\').replace("'", "\\'")
                items.append(f"'{item_str}'")
            else:
                items.append(repr(item))
        return f"[{', '.join(items)}]"
    elif isinstance(value, dict):
        if len(value) == 0:
            return "{}"
        items = []
        for k, v in value.items():
            key_str = f"'{k}'" if isinstance(k, str) else str(k)
            val_str = format_field_value(v)
            items.append(f"{key_str}: {val_str}")
        return f"{{{', '.join(items)}}}"
    else:
        return repr(value)

def generate_override_code(fixes: Dict[str, Dict]) -> str:
    """Tạo code Python để thêm vào enhanced_fields_overrides.py"""
    if not fixes:
        return None
    
    lines = []
    lines.append("")
    lines.append("# Auto-generated fixes from validation")
    lines.append("# Generated by apply_auto_fixes_to_file.py")
    lines.append("")
    lines.append("EXTRA_ENHANCED_FIELDS.update({")
    
    for drug_name, fields in sorted(fixes.items()):
        lines.append(f"    \"{drug_name}\": {{")
        for field_name, field_value in fields.items():
            # Format field value
            if isinstance(field_value, dict):
                # Multi-line dict
                lines.append(f"        \"{field_name}\": {{")
                for k, v in field_value.items():
                    if isinstance(v, dict):
                        lines.append(f"            \"{k}\": {{")
                        for k2, v2 in v.items():
                            val_str = format_field_value(v2)
                            lines.append(f"                \"{k2}\": {val_str},")
                        lines.append("            },")
                    elif isinstance(v, list):
                        val_str = format_field_value(v)
                        lines.append(f"            \"{k}\": {val_str},")
                    else:
                        val_str = format_field_value(v)
                        lines.append(f"            \"{k}\": {val_str},")
                lines.append("        },")
            elif isinstance(field_value, list):
                val_str = format_field_value(field_value)
                lines.append(f"        \"{field_name}\": {val_str},")
            else:
                val_str = format_field_value(field_value)
                lines.append(f"        \"{field_name}\": {val_str},")
        lines.append("    },")
    
    lines.append("})")
    lines.append("")
    
    return "\n".join(lines)

def apply_fixes_to_file():
    """Áp dụng các sửa lỗi vào enhanced_fields_overrides.py"""
    print("=" * 100)
    print("ÁP DỤNG CÁC SỬA LỖI TỰ ĐỘNG VÀO FILE")
    print("=" * 100)
    print()
    
    # Lấy các sửa lỗi
    print("Đang phân tích các sửa lỗi...")
    fixes = get_drug_fixes_from_memory()
    
    if not fixes:
        print("⚠️  Không có lỗi nào cần sửa")
        return
    
    print(f"✅ Tìm thấy {len(fixes)} thuốc cần sửa:")
    for drug_name in sorted(fixes.keys()):
        print(f"   - {drug_name}: {', '.join(fixes[drug_name].keys())}")
    
    # Tạo code
    print("\nĐang tạo code Python...")
    code = generate_override_code(fixes)
    
    if not code:
        print("⚠️  Không thể tạo code")
        return
    
    # Lưu vào file
    output_file = "auto_fix_code_to_add.py"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(code)
    
    print(f"✅ Đã tạo file: {output_file}")
    print()
    print("=" * 100)
    print("HƯỚNG DẪN SỬ DỤNG")
    print("=" * 100)
    print()
    print("1. Kiểm tra file auto_fix_code_to_add.py")
    print("2. Copy nội dung vào cuối file drugs/enhanced_fields_overrides.py")
    print("3. Hoặc chạy lệnh sau để tự động thêm:")
    print()
    print(f"   type {output_file} >> drugs\\enhanced_fields_overrides.py")
    print()
    print("⚠️  LƯU Ý:")
    print("   - Backup file enhanced_fields_overrides.py trước khi sửa")
    print("   - Kiểm tra lại code trước khi áp dụng")
    print("   - Chạy lại validation sau khi áp dụng")
    print()
    
    # Hiển thị preview
    print("=" * 100)
    print("PREVIEW CODE (50 dòng đầu):")
    print("=" * 100)
    preview_lines = code.split('\n')[:50]
    for line in preview_lines:
        print(line)
    if len(code.split('\n')) > 50:
        print(f"... và {len(code.split('\n')) - 50} dòng khác")

def main():
    """Hàm chính"""
    try:
        apply_fixes_to_file()
    except Exception as e:
        print(f"❌ Lỗi: {e}")
        import traceback
        traceback.print_exc()

if __name__ == '__main__':
    main()

