
# Auto-generated fixes from validation
# Generated by apply_auto_fixes_to_file.py

EXTRA_ENHANCED_FIELDS.update({
    "Abaloparatide": {
        "interactions": ['Chưa có báo cáo tương tác thuốc đáng kể'],
    },
    "Alirocumab": {
        "overdose_management": {
            "symptoms": ['Cần đánh giá lâm sàng'],
            "antidote": 'Không có antidote đặc hiệu',
            "treatment": ['Chưa có báo cáo quá liều. Nếu tiêm quá liều, theo dõi các tác dụng phụ và điều trị hỗ trợ.'],
            "monitoring": 'Theo dõi dấu hiệu sinh tồn và triệu chứng',
        },
        "administration_instructions": {
            "oral": {
                "with_food": 'Tiêm dưới da (bụng, đùi, hoặc cánh tay). Để ở nhiệt độ phòng 30 phút trước khi tiêm. Không lắc. Luân phiên vị trí tiêm. Có thể tự tiêm sau khi được hướng dẫn.',
                "timing": 'Theo chỉ định của bác sĩ',
            },
            "iv": {
                "reconstitution": 'N/A',
                "infusion_rate": 'N/A',
                "compatibility": [],
                "incompatibility": [],
                "notes": 'N/A',
            },
        },
    },
    "Amlodipine/Olmesartan": {
        "interactions": ['Chưa có báo cáo tương tác thuốc đáng kể'],
    },
    "Calcitonin": {
        "interactions": ['Chưa có báo cáo tương tác thuốc đáng kể'],
    },
    "Enalapril": {
        "guideline_tags": ['C09AA02', '24.08.08 ACE Inhibitors', 'vietnam_essential_medicines: True', {'source': 'ESC 2021 Heart Failure', 'recommendation': 'ACE inhibitor first-line therapy for HFrEF if tolerated', 'context': 'Heart failure with reduced ejection fraction (HFrEF), NYHA II–III'}, {'source': 'ACC/AHA 2017 Hypertension Guideline', 'recommendation': 'One of the first-line options for hypertension', 'context': 'Primary hypertension, non-black, with or without diabetes'}, {'source': 'BYT – Hướng dẫn chẩn đoán và điều trị tăng huyết áp 2020', 'recommendation': 'Một trong các lựa chọn hàng đầu điều trị tăng huyết áp', 'context': 'Tăng huyết áp nguyên phát không biến chứng, ưu tiên bệnh nhân có đái tháo đường hoặc bệnh thận mạn'}, 'first_line_htn', 'hfref_mortality_benefit', 'ckd_proteinuria_bp_control'],
    },
    "Evolocumab": {
        "overdose_management": {
            "symptoms": ['Cần đánh giá lâm sàng'],
            "antidote": 'Không có antidote đặc hiệu',
            "treatment": ['Chưa có báo cáo quá liều. Nếu tiêm quá liều, theo dõi các tác dụng phụ và điều trị hỗ trợ.'],
            "monitoring": 'Theo dõi dấu hiệu sinh tồn và triệu chứng',
        },
        "administration_instructions": {
            "oral": {
                "with_food": 'Tiêm dưới da (bụng, đùi, hoặc cánh tay). Để ở nhiệt độ phòng 30 phút trước khi tiêm. Không lắc. Luân phiên vị trí tiêm. Có thể tự tiêm sau khi được hướng dẫn.',
                "timing": 'Theo chỉ định của bác sĩ',
            },
            "iv": {
                "reconstitution": 'N/A',
                "infusion_rate": 'N/A',
                "compatibility": [],
                "incompatibility": [],
                "notes": 'N/A',
            },
        },
    },
    "Inclisiran": {
        "overdose_management": {
            "symptoms": ['Cần đánh giá lâm sàng'],
            "antidote": 'Không có antidote đặc hiệu',
            "treatment": ['Chưa có báo cáo quá liều. Nếu tiêm quá liều, theo dõi các tác dụng phụ và điều trị hỗ trợ.'],
            "monitoring": 'Theo dõi dấu hiệu sinh tồn và triệu chứng',
        },
        "administration_instructions": {
            "oral": {
                "with_food": 'Tiêm dưới da (bụng, đùi, hoặc cánh tay). Để ở nhiệt độ phòng 30 phút trước khi tiêm. Không lắc. Luân phiên vị trí tiêm. Có thể tự tiêm sau khi được hướng dẫn. Lịch tiêm: Liều đầu tiên, sau đó liều thứ 2 sau 3 tháng, sau đó mỗi 6 tháng.',
                "timing": 'Theo chỉ định của bác sĩ',
            },
            "iv": {
                "reconstitution": 'N/A',
                "infusion_rate": 'N/A',
                "compatibility": [],
                "incompatibility": [],
                "notes": 'N/A',
            },
        },
    },
    "Lisinopril": {
        "guideline_tags": ['C09AA03', '24.08.08 ACE Inhibitors', 'vietnam_essential_medicines: True', {'source': 'ESC 2021 Heart Failure', 'recommendation': 'ACE inhibitor first-line therapy for HFrEF if ARNI not available', 'context': 'Heart failure with reduced ejection fraction (HFrEF), NYHA II–III'}, {'source': 'BYT – Hướng dẫn chẩn đoán và điều trị suy tim 2015', 'recommendation': 'Thuốc nền tảng trong điều trị suy tim HFrEF cùng với beta-blocker và mineralocorticoid receptor antagonist', 'context': 'Suy tim mạn HFrEF, NYHA II–IV'}, 'first_line_htn', 'hfref_mortality_benefit'],
    },
    "Losartan": {
        "guideline_tags": ['C09CA01', '24.08.06 Angiotensin II Receptor Blockers', 'vietnam_essential_medicines: True', {'source': 'ACC/AHA 2017 Hypertension Guideline', 'recommendation': 'ARB as alternative first-line when ACE inhibitors not tolerated', 'context': 'Primary hypertension, ACE inhibitor intolerance (e.g. cough, angioedema)'}, {'source': 'BYT – Hướng dẫn chẩn đoán và điều trị tăng huyết áp 2020', 'recommendation': 'Lựa chọn khi không dung nạp ACEI hoặc cần bảo vệ thận', 'context': 'Tăng huyết áp có đái tháo đường hoặc bệnh thận mạn'}, 'first_line_htn_alt_acei', 'ckd_diabetic_nephropathy'],
    },
    "Metformin": {
        "guideline_tags": ['A10BA02', '68.20.08 Biguanides', 'vietnam_essential_medicines: True', {'source': 'ADA 2024 Standards of Care', 'recommendation': 'Initial pharmacologic therapy for most adults with type 2 diabetes', 'context': 'Type 2 diabetes without contraindications; often combined with lifestyle changes'}, {'source': 'BYT – Hướng dẫn chẩn đoán và điều trị đái tháo đường typ 2', 'recommendation': 'Thuốc đầu tay trong điều trị đái tháo đường typ 2 nếu không chống chỉ định', 'context': 'ĐTĐ typ 2, không suy thận nặng hoặc chống chỉ định khác'}, 'first_line_t2dm', 'weight_neutral_or_loss', 'low_hypoglycemia_risk'],
    },
    "Romosozumab": {
        "interactions": ['Chưa có báo cáo tương tác thuốc đáng kể'],
    },
    "Spironolactone": {
        "guideline_tags": ['C03DA01', '24.08.04 Aldosterone Antagonists', 'vietnam_essential_medicines: True', {'source': 'ESC 2021 Heart Failure', 'recommendation': 'Mineralocorticoid receptor antagonist to reduce mortality', 'context': 'HFrEF with persistent symptoms despite ACEI/ARB/ARNI and beta-blocker'}, 'hfref_mortality_benefit', 'hyperaldosteronism'],
    },
    "Tegoprazan": {
        "overdose_management": {
            "symptoms": ['Cần đánh giá lâm sàng'],
            "antidote": 'Không có antidote đặc hiệu',
            "treatment": ['Triệu chứng: Buồn nôn, nôn, đau bụng. Điều trị: Hỗ trợ, rửa dạ dày nếu mới uống.'],
            "monitoring": 'Theo dõi dấu hiệu sinh tồn và triệu chứng',
        },
        "administration_instructions": {
            "oral": {
                "with_food": 'Uống với hoặc không có thức ăn. Nuốt nguyên viên, không nhai hoặc nghiền.',
                "timing": 'Theo chỉ định của bác sĩ',
            },
            "iv": {
                "reconstitution": 'N/A',
                "infusion_rate": 'N/A',
                "compatibility": [],
                "incompatibility": [],
                "notes": 'Chỉ có dạng uống',
            },
        },
    },
    "Vonoprazan": {
        "overdose_management": {
            "symptoms": ['Cần đánh giá lâm sàng'],
            "antidote": 'Không có antidote đặc hiệu',
            "treatment": ['Triệu chứng: Buồn nôn, nôn, đau bụng. Điều trị: Hỗ trợ, rửa dạ dày nếu mới uống. Không có chất đối kháng đặc hiệu.'],
            "monitoring": 'Theo dõi dấu hiệu sinh tồn và triệu chứng',
        },
        "administration_instructions": {
            "oral": {
                "with_food": 'Uống với hoặc không có thức ăn. Không cần uống trước bữa ăn như PPI. Nuốt nguyên viên, không nhai hoặc nghiền.',
                "timing": 'Theo chỉ định của bác sĩ',
            },
            "iv": {
                "reconstitution": 'N/A',
                "infusion_rate": 'N/A',
                "compatibility": [],
                "incompatibility": [],
                "notes": 'Chỉ có dạng uống',
            },
        },
    },
})
