"""
Templates cho enhanced fields
Generated by generate_field_templates.py
"""

FIELD_TEMPLATES = {
    "contraindications_detail": """\"contraindications_detail\": {\n    \"tuyệt_đối\": [\n        \"Dị ứng thuốc\",\n        \"Chống chỉ định cụ thể\"\n    ],\n    \"tương_đối\": [\n        \"Thận trọng trong trường hợp\",\n        \"Cần điều chỉnh liều\"\n    ]\n}""",
    "reversal_agents": """\"reversal_agents\": {\n    \"available\": True,  # hoặc False nếu không có\n    \"agents\": [\n        {\n            \"name\": \"Tên thuốc giải độc\",\n            \"dose\": \"Liều dùng\",\n            \"route\": \"Đường dùng\",\n            \"notes\": \"Ghi chú\"\n        }\n    ]\n}""",
    "black_box_warnings": """\"black_box_warnings\": \"Cảnh báo đặc biệt quan trọng về an toàn. Mô tả chi tiết các nguy cơ nghiêm trọng.\"""",
    "renal_adjustment": """\"renal_adjustment\": {\n    \"normal\": \"Không đổi\",\n    \"30_60\": \"Giảm liều X%\",\n    \"under_30\": \"Giảm liều X% hoặc không dùng\",\n    \"notes\": \"Ghi chú thêm\"\n}""",
    "hepatic_adjustment": """\"hepatic_adjustment\": {\n    \"mild\": \"Không đổi hoặc giảm liều X%\",\n    \"moderate\": \"Giảm liều X%\",\n    \"severe\": \"Không dùng hoặc giảm liều X%\",\n    \"notes\": \"Ghi chú thêm\"\n}""",
    "drug_interactions": """\"drug_interactions\": {\n    \"major\": [\n        {\n            \"drug\": \"Tên thuốc\",\n            \"mechanism\": \"Cơ chế tương tác\",\n            \"effect\": \"Tác dụng\",\n            \"management\": \"Cách xử lý\"\n        }\n    ],\n    \"moderate\": [],\n    \"minor\": []\n}""",
    "pregnancy_lactation": """\"pregnancy_lactation\": {\n    \"fda_category\": \"X\",  # A, B, C, D, hoặc X\n    \"pregnancy_details\": \"Chi tiết về sử dụng trong thai kỳ\",\n    \"lactation\": {\n        \"safety\": \"Compatible/Incompatible/Unknown\",\n        \"details\": \"Chi tiết về sử dụng khi cho con bú\",\n        \"recommendation\": \"Khuyến nghị\"\n    }\n}""",
    "overdose_management": """\"overdose_management\": {\n    \"symptoms\": [\n        \"Triệu chứng 1\",\n        \"Triệu chứng 2\"\n    ],\n    \"antidote\": \"Tên antidote hoặc 'Không có antidote đặc hiệu'\",\n    \"treatment\": [\n        \"Bước điều trị 1\",\n        \"Bước điều trị 2\"\n    ],\n    \"monitoring\": \"Theo dõi các dấu hiệu sinh tồn và triệu chứng\"\n}""",
    "administration_instructions": """\"administration_instructions\": {\n    \"oral\": {\n        \"with_food\": \"Uống với thức ăn hoặc không\",\n        \"timing\": \"Thời điểm uống\"\n    },\n    \"iv\": {\n        \"reconstitution\": \"Cách pha\",\n        \"infusion_rate\": \"Tốc độ truyền\",\n        \"compatibility\": [\"Thuốc tương thích\"],\n        \"incompatibility\": [\"Thuốc không tương thích\"],\n        \"notes\": \"Ghi chú thêm\"\n    }\n}""",
}