"""
Patient Education Display Functions
Render patient education content
"""

import streamlit as st
from typing import Optional
from patient_education.data import PatientEducationTopic


def render_patient_education_content(topic: PatientEducationTopic):
    """
    Render patient education content and related resources.

    Lịch sử:
    - Ban đầu hàm này chỉ dùng `st.markdown(topic.content)` (không cho phép HTML),
      dẫn đến các topic chứa HTML (ví dụ `<div style=\"...\">`) bị hiển thị thô.
    - Hiện tại chúng ta cho phép HTML để nội dung luôn hiển thị đúng.
    """
    # Cho phép HTML trong nội dung topic để các đoạn được format bằng HTML
    # (ví dụ badges, layout) không bị escape thành text thô.
    st.markdown(topic.content, unsafe_allow_html=True)

    # Related resources
    if topic.related_disease or topic.related_drugs:
        st.markdown("---")
        st.markdown("### 🔗 Tài nguyên Liên quan")
        
        if topic.related_disease:
            st.markdown(f"**Bệnh lý:** {topic.related_disease}")
            st.markdown(f"💡 Xem thêm trong [Bách khoa Bệnh lý](?page=16_📖_Disease_Encyclopedia)")
        
        if topic.related_drugs:
            st.markdown(f"**Thuốc liên quan:** {', '.join(topic.related_drugs)}")
            st.markdown(f"💡 Xem thêm trong [Cơ sở dữ liệu thuốc](?page=07_💊_Drug_Database)")


def get_patient_education_pdf(topic: PatientEducationTopic) -> Optional[str]:
    """
    Generate PDF content for patient education (placeholder)
    In future, can use reportlab to generate actual PDF
    
    Args:
        topic: PatientEducationTopic object
        
    Returns:
        PDF content as string (placeholder)
    """
    # Placeholder - can implement actual PDF generation later
    return f"""
PATIENT EDUCATION HANDOUT
========================

Title: {topic.title_vn}
Category: {topic.category}

{topic.content}

---
Generated by Clinical Assistant
For educational purposes only
    """

