"""
Patient Education Display Functions
Render patient education content
"""

import streamlit as st
import textwrap
from typing import Optional
from patient_education.data import PatientEducationTopic


def render_patient_education_content(topic: PatientEducationTopic):
    """
    Render patient education content and related resources.

    - Chuẩn hóa nội dung (bỏ thụt lề chung, khoảng trắng dư) để Markdown không
      hiểu nhầm là code block.
    - Cho phép HTML trong nội dung topic để các đoạn được format bằng HTML
      (ví dụ badges, layout) hiển thị đúng thay vì bị escape.
    """
    raw_content = topic.content or ""
    normalized_content = textwrap.dedent(raw_content).strip()

    st.markdown(normalized_content, unsafe_allow_html=True)

    # Related resources
    if topic.related_disease or topic.related_drugs:
        st.markdown("---")
        st.markdown("### 🔗 Tài nguyên Liên quan")
        
        if topic.related_disease:
            st.markdown(f"**Bệnh lý:** {topic.related_disease}")
            st.markdown(f"💡 Xem thêm trong [Bách khoa Bệnh lý](?page=16_📖_Disease_Encyclopedia)")
        
        if topic.related_drugs:
            st.markdown(f"**Thuốc liên quan:** {', '.join(topic.related_drugs)}")
            st.markdown(f"💡 Xem thêm trong [Cơ sở dữ liệu thuốc](?page=07_💊_Drug_Database)")


def get_patient_education_pdf(topic: PatientEducationTopic) -> Optional[str]:
    """
    Generate PDF content for patient education (placeholder)
    In future, can use reportlab to generate actual PDF
    
    Args:
        topic: PatientEducationTopic object
        
    Returns:
        PDF content as string (placeholder)
    """
    # Placeholder - can implement actual PDF generation later
    return f"""
PATIENT EDUCATION HANDOUT
========================

Title: {topic.title_vn}
Category: {topic.category}

{topic.content}

---
Generated by Clinical Assistant
For educational purposes only
    """

