"""
Configuration file for all scoring systems
Defines available calculators organized by specialty
"""

SCORES_BY_SPECIALTY = {
    "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)": {
        "NEWS2": {"name": "NEWS2 - National Early Warning Score 2", "desc": "Hệ thống cảnh báo sớm cho bệnh nhân nội trú (DÙNG HÀNG NGÀY)", "status": "✅"},
        "MEWS": {"name": "MEWS - Modified Early Warning Score", "desc": "Hệ thống cảnh báo sớm - Phát hiện tình trạng xấu đi (DÙNG HÀNG NGÀY)", "status": "✅"},
        "qSOFA": {"name": "qSOFA - Quick SOFA", "desc": "Sàng lọc nhiễm trùng huyết", "status": "✅"},
        "SOFA": {"name": "SOFA - Sequential Organ Failure Assessment", "desc": "Đánh giá suy cơ quan", "status": "✅"},
        "SOFA-2 (2025)": {"name": "SOFA-2 (2025) ⭐", "desc": "SOFA cập nhật 2025 - HFNC, ECMO, RRT, vasopressor mới", "status": "✅"},
        "APACHE II": {"name": "APACHE II", "desc": "Dự đoán tử vong ICU", "status": "✅"},
        "APACHE III": {"name": "APACHE III - Acute Physiology and Chronic Health Evaluation III", "desc": "Dự đoán tử vong ICU - Phiên bản cập nhật (chính xác hơn APACHE II)", "status": "✅"},
        "APACHE IV": {"name": "APACHE IV ⭐", "desc": "Dự đoán tử vong ICU - Phiên bản mới nhất 2006 (chính xác nhất)", "status": "✅"},
        "SAPS II": {"name": "SAPS II - Simplified Acute Physiology Score", "desc": "Độ nặng bệnh nhân ICU", "status": "✅"},
        "SAPS III": {"name": "SAPS III - Simplified Acute Physiology Score III", "desc": "Dự đoán tử vong ICU - Phiên bản cập nhật (chính xác hơn SAPS II)", "status": "✅"},
        "MODS": {"name": "MODS - Multiple Organ Dysfunction Score", "desc": "Rối loạn đa cơ quan", "status": "✅"},
        "LODS": {"name": "LODS - Logistic Organ Dysfunction Score", "desc": "Đánh giá suy cơ quan trong ICU", "status": "✅"},
        "HOSPITAL Score": {"name": "HOSPITAL Score", "desc": "Dự đoán tái nhập viện 30 ngày", "status": "✅"},
        "LACE Index": {"name": "LACE Index", "desc": "Dự đoán tái nhập viện hoặc tử vong 30 ngày", "status": "✅"},
        "Alvarado Score": {"name": "Alvarado Score ⭐", "desc": "Dự đoán viêm ruột thừa cấp (DÙNG HÀNG NGÀY)", "status": "✅"},
        "ROX Index": {"name": "ROX Index ⭐", "desc": "Dự đoán thất bại HFNC (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Lactate Clearance": {"name": "Lactate Clearance ⭐", "desc": "Đánh giá hiệu quả hồi sức sốc (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Charlson Index": {"name": "Charlson Comorbidity Index ⭐", "desc": "Dự đoán tử vong 10 năm dựa trên bệnh lý mạn tính (DÙNG RỘNG RÃI)", "status": "✅"},
        "CRB-65 Score": {"name": "CRB-65 Score ⭐", "desc": "Phân tầng mức độ nặng viêm phổi cộng đồng - Quyết định nội trú/ngoại trú (DÙNG HÀNG NGÀY)", "status": "✅"},
        "SCORTEN Score": {"name": "SCORTEN Score ⭐", "desc": "Ước tính nguy cơ tử vong ở bệnh nhân SJS/TEN", "status": "✅"},
        "RDOS": {"name": "RDOS ⭐", "desc": "Định lượng suy hô hấp ở bệnh nhân không thể tự báo cáo triệu chứng", "status": "✅"},
    },
    
    "❤️ Tim mạch (Cardiology)": {
        "ASCVD Risk": {"name": "ASCVD Risk Calculator ⭐", "desc": "Nguy cơ tim mạch 10 năm - ACC/AHA Pooled Cohort Equations (THAY THẾ FRAMINGHAM)", "status": "✅"},
        "NYHA": {"name": "NYHA Classification", "desc": "Phân loại chức năng suy tim (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Killip": {"name": "Killip Classification", "desc": "Suy tim cấp trong AMI (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Duke": {"name": "Duke Criteria", "desc": "Chẩn đoán viêm nội tâm mạc", "status": "✅"},
        "CHA2DS2-VASc": {"name": "CHA₂DS₂-VASc", "desc": "Nguy cơ đột quỵ trong rung nhĩ", "status": "✅"},
        "HAS-BLED": {"name": "HAS-BLED", "desc": "Nguy cơ chảy máu khi dùng kháng đông", "status": "✅"},
        "SCORE2": {"name": "SCORE2", "desc": "Nguy cơ tim mạch 10 năm (40-69 tuổi)", "status": "✅"},
        "SCORE2-OP": {"name": "SCORE2-OP", "desc": "Nguy cơ tim mạch (≥70 tuổi)", "status": "✅"},
        "HEART Score": {"name": "HEART Score", "desc": "Đau ngực cấp - nguy cơ ACS", "status": "✅"},
        "TIMI Risk": {"name": "TIMI Risk Score", "desc": "Nguy cơ NSTEMI/STEMI", "status": "✅"},
        "GRACE Score": {"name": "GRACE Score", "desc": "Tiên lượng ACS", "status": "✅"},
        "CRUSADE Score": {"name": "CRUSADE Bleeding Risk Score ⭐", "desc": "Nguy cơ chảy máu trong ACS (DÙNG HÀNG NGÀY)", "status": "✅"},
        "PRECISE-DAPT": {"name": "PRECISE-DAPT Score ⭐", "desc": "Nguy cơ chảy máu khi dùng DAPT (DÙNG HÀNG NGÀY)", "status": "✅"},
        "DAPT Score": {"name": "DAPT Score ⭐", "desc": "Thời gian dùng DAPT sau PCI (DÙNG HÀNG NGÀY)", "status": "✅"},
        "ARC-HBR Criteria": {"name": "ARC-HBR Criteria ⭐⭐", "desc": "Xác định nguy cơ chảy máu cao ở bệnh nhân PCI (DÙNG HÀNG NGÀY)", "status": "✅"},
        "PCP-HF Risk Score": {"name": "PCP-HF Risk Score ⭐", "desc": "Ước tính nguy cơ 10 năm của suy tim mới khởi phát ở người lớn không có triệu chứng", "status": "✅"},
        "Framingham": {"name": "Framingham Risk Score", "desc": "Nguy cơ tim mạch 10 năm (Historical)", "status": "✅"},
        "Corrected QT": {"name": "QTc - Corrected QT Interval", "desc": "QT điều chỉnh theo nhịp tim", "status": "✅"},
        "HFA-ICOS Multiple Myeloma": {"name": "HFA-ICOS Multiple Myeloma Risk ⭐⭐⭐", "desc": "Đánh giá nguy cơ tim mạch trước điều trị đa u tủy xương (MỚI 2024-2025)", "status": "✅"},
        "HFA-ICOS CML TKI": {"name": "HFA-ICOS CML TKI Risk ⭐⭐⭐", "desc": "Đánh giá nguy cơ tim mạch trước điều trị CML bằng TKI (MỚI 2024-2025)", "status": "✅"},
        "HFA-ICOS RAF/MEK": {"name": "HFA-ICOS RAF/MEK Inhibitors Risk ⭐⭐⭐", "desc": "Đánh giá nguy cơ tim mạch trước điều trị RAF/MEK inhibitors (MỚI 2024-2025)", "status": "✅"},
        "HFA-ICOS VEGF": {"name": "HFA-ICOS VEGF Inhibitors Risk ⭐⭐⭐", "desc": "Đánh giá nguy cơ tim mạch trước điều trị VEGF inhibitors (MỚI 2024-2025)", "status": "✅"},
        "HFA-ICOS HER2": {"name": "HFA-ICOS HER2-Targeted Therapies Risk ⭐⭐⭐", "desc": "Đánh giá nguy cơ tim mạch trước điều trị HER2-targeted therapies (MỚI 2024-2025)", "status": "✅"},
        "HFA-ICOS Anthracycline": {"name": "HFA-ICOS Anthracycline Risk ⭐⭐⭐", "desc": "Đánh giá nguy cơ tim mạch trước điều trị anthracycline (MỚI 2024-2025)", "status": "✅"},
    },
    
    "🫁 Hô hấp (Respiratory)": {
        "PERC": {"name": "PERC Rule", "desc": "Loại trừ PE không cần D-dimer (DÙNG HÀNG NGÀY)", "status": "✅"},
        "CURB-65": {"name": "CURB-65", "desc": "Mức độ nặng viêm phổi", "status": "✅"},
        "PSI/PORT": {"name": "PSI/PORT Score", "desc": "Tiên lượng viêm phổi cộng đồng", "status": "✅"},
        "Wells PE": {"name": "Wells PE Score", "desc": "Nguy cơ thuyên tắc phổi", "status": "✅"},
        "PESI": {"name": "PESI - Pulmonary Embolism Severity Index", "desc": "Mức độ nặng và tiên lượng thuyên tắc phổi", "status": "✅"},
        "SMART-COP": {"name": "SMART-COP", "desc": "Cần hỗ trợ hô hấp trong viêm phổi", "status": "✅"},
        "BODE Index": {"name": "BODE Index", "desc": "Tiên lượng COPD", "status": "✅"},
        "ARDS Berlin": {"name": "ARDS Berlin Definition", "desc": "Tiêu chuẩn chẩn đoán ARDS (Berlin 2012)", "status": "✅"},
        "mMRC": {"name": "mMRC Dyspnea Scale ⭐", "desc": "Đánh giá mức độ khó thở ở COPD (DÙNG HÀNG NGÀY)", "status": "✅"},
        "ACT": {"name": "Asthma Control Test (ACT) ⭐", "desc": "Đánh giá mức độ kiểm soát hen phế quản (DÙNG HÀNG NGÀY)", "status": "✅"},
    },
    
    "🧠 Thần kinh (Neurology)": {
        "GCS": {"name": "GCS - Thang điểm hôn mê Glasgow (Thang điểm hôn mê Glasgow)", "desc": "Mức độ ý thức", "status": "✅"},
        "NIHSS": {"name": "NIHSS - NIH Stroke Scale", "desc": "Mức độ nặng đột quỵ", "status": "✅"},
        "ICH Score": {"name": "ICH Score", "desc": "Tiên lượng xuất huyết nội sọ", "status": "✅"},
        "Hunt & Hess": {"name": "Hunt & Hess Scale", "desc": "Phân loại xuất huyết dưới nhện", "status": "✅"},
        "mRS": {"name": "mRS - Modified Rankin Scale", "desc": "Mức độ khuyết tật sau đột quỵ", "status": "✅"},
        "ASPECTS": {"name": "ASPECTS - Alberta Stroke Program Early CT Score", "desc": "Đánh giá thay đổi thiếu máu sớm trên CT - Quyết định thrombolysis/thrombectomy", "status": "✅"},
        "ABCD2": {"name": "ABCD2 Score", "desc": "Phân tầng nguy cơ đột quỵ sau TIA", "status": "✅"},
        "Barthel Index": {"name": "Barthel Index", "desc": "Đánh giá chức năng hoạt động hàng ngày (ADL)", "status": "✅"},
        "FOUR Score": {"name": "FOUR Score - Full Outline of UnResponsiveness", "desc": "Đánh giá mức độ ý thức - Thay thế GCS cho bệnh nhân thở máy", "status": "✅"},
        "Canadian CT Head": {"name": "Canadian CT Head Rule ⭐", "desc": "Quyết định chụp CT đầu ở chấn thương đầu nhẹ (người lớn)", "status": "✅"},
        "FAST-ED": {"name": "FAST-ED Score ⭐⭐", "desc": "Xác định đột quỵ tắc mạch lớn (LVOS) trong môi trường tiền viện (DÙNG HÀNG NGÀY)", "status": "✅"},
        "ICANS Consensus Grading": {"name": "ICANS Consensus Grading ⭐⭐⭐", "desc": "Phân độ mức độ nặng của độc tính thần kinh gây ra bởi liệu pháp tế bào hiệu ứng miễn dịch như CAR T-cell (MỚI, QUAN TRỌNG)", "status": "✅"},
        "Sudbury Vertigo Risk Score": {"name": "Sudbury Vertigo Risk Score ⭐", "desc": "Xác định bệnh nhân chóng mặt có nguy cơ tăng cao chẩn đoán trung ương nghiêm trọng", "status": "✅"},
        "MGFA Clinical Classification": {"name": "MGFA Clinical Classification ⭐", "desc": "Phân loại mức độ nặng của bệnh nhược cơ", "status": "✅"},
        "MG-ADL": {"name": "MG-ADL ⭐", "desc": "Đánh giá mức độ nặng bệnh ở bệnh nhân nhược cơ (MG)", "status": "✅"},
        "ICE Score": {"name": "ICE Score ⭐", "desc": "Đánh giá độc tính thần kinh ở bệnh nhân điều trị CAR T-cell (Immune Effector Cell Encephalopathy)", "status": "✅"},
    },
    
    "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)": {
        "BISAP": {"name": "BISAP Score", "desc": "Tiên lượng viêm tụy cấp (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Child-Pugh": {"name": "Child-Pugh Score", "desc": "Mức độ xơ gan", "status": "✅"},
        "MELD": {"name": "MELD Score", "desc": "Tiên lượng bệnh gan mạn & ghép gan", "status": "✅"},
        "Glasgow-Blatchford": {"name": "Glasgow-Blatchford Score", "desc": "UGIB - quyết định xuất viện", "status": "✅"},
        "AIMS65": {"name": "AIMS65 Score", "desc": "UGIB - dự đoán tử vong (đơn giản, 5 yếu tố)", "status": "✅"},
        "Rockall Score": {"name": "Rockall Score", "desc": "UGIB - tiên lượng tử vong", "status": "✅"},
        "MELD-Na": {"name": "MELD-Na", "desc": "MELD điều chỉnh theo Na", "status": "✅"},
        "Ranson": {"name": "Ranson Criteria", "desc": "Tiên lượng viêm tụy cấp", "status": "✅"},
        "FIB-4": {"name": "FIB-4 Index ⭐", "desc": "Đánh giá xơ hóa gan không xâm lấn (HCV, HBV, NAFLD)", "status": "✅"},
        "Acute Pancreatitis Prediction": {"name": "Acute Pancreatitis Prediction Model ⭐", "desc": "Ước tính khả năng viêm tụy cấp ở bệnh nhân có lipase tăng cao trước khi xác nhận bằng hình ảnh", "status": "✅"},
        "SAFE Score": {"name": "SAFE Score ⭐", "desc": "Ước tính nguy cơ xơ hóa gan trung bình đến tiến triển (F2+) ở bệnh nhân MASLD", "status": "✅"},
        "EREFS": {"name": "EREFS ⭐", "desc": "Đánh giá mức độ nặng của các phát hiện nội soi ở bệnh nhân viêm thực quản tăng bạch cầu ái toan (EoE)", "status": "✅"},
    },
    
    "🩺 Huyết học & Đông máu (Hematology)": {
        "Padua": {"name": "Padua Prediction Score", "desc": "Nguy cơ VTE - Chỉ định prophylaxis (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Wells DVT": {"name": "Wells DVT Score", "desc": "Nguy cơ huyết khối tĩnh mạch sâu", "status": "✅"},
        "4Ts Score": {"name": "4Ts Score - HIT", "desc": "Giảm tiểu cầu do heparin", "status": "✅"},
        "DIC Score": {"name": "DIC Score (ISTH)", "desc": "Đông máu rải rác trong lòng mạch", "status": "✅"},
    },
    
    "🧪 Thận - Điện giải (Nephrology)": {
        "eGFR": {"name": "eGFR - CKD-EPI & MDRD", "desc": "Tính tốc độ lọc cầu thận (DÙNG HÀNG NGÀY)", "status": "✅"},
        "KDIGO": {"name": "KDIGO Staging", "desc": "Giai đoạn AKI (Tiêu chuẩn hiện đại)", "status": "✅"},
        "RIFLE": {"name": "RIFLE Criteria", "desc": "Phân loại AKI (Historical)", "status": "✅"},
        "AKIN": {"name": "AKIN Criteria", "desc": "Suy thận cấp (Historical)", "status": "✅"},
    },
    
    "🦴 Chấn thương & Chỉnh Hình (Trauma/Orthopedics)": {
        "RTS": {"name": "RTS - Revised Trauma Score", "desc": "Tiên lượng chấn thương (sinh lý)", "status": "✅"},
        "ISS": {"name": "ISS - Injury Severity Score", "desc": "Mức độ nặng đa chấn thương (giải phẫu)", "status": "✅"},
        "NEXUS": {"name": "NEXUS C-Spine", "desc": "Cần chụp X-quang cột sống cổ", "status": "✅"},
        "Canadian C-Spine": {"name": "Canadian C-Spine Rule", "desc": "Chỉ định chụp cột sống cổ", "status": "✅"},
        "TRISS": {"name": "TRISS - Trauma and Injury Severity Score", "desc": "Dự đoán khả năng sống sót sau chấn thương", "status": "✅"},
    },
    
    "👂 Tai Mũi Họng (ENT)": {
        "Epworth": {"name": "Epworth Sleepiness Scale", "desc": "Đánh giá buồn ngủ ban ngày", "status": "✅"},
        "STOP-BANG": {"name": "STOP-BANG Score", "desc": "Sàng lọc OSA", "status": "✅"},
    },
    
    "👶 Nhi khoa (Pediatrics)": {
        "Westley Croup": {"name": "Westley Croup Score", "desc": "Mức độ nặng croup (DÙNG HÀNG NGÀY)", "status": "✅"},
        "PEWS": {"name": "PEWS - Pediatric Early Warning Score", "desc": "Cảnh báo sớm nhi", "status": "✅"},
        "APGAR": {"name": "APGAR Score", "desc": "Đánh giá trẻ sơ sinh", "status": "✅"},
        "Pediatric GCS": {"name": "Pediatric GCS", "desc": "Ý thức trẻ em", "status": "✅"},
        "PELOD-2": {"name": "PELOD-2 - Pediatric Logistic Organ Dysfunction", "desc": "Suy đa cơ quan ICU nhi", "status": "✅"},
        "PRISM III": {"name": "PRISM III - Pediatric Risk of Mortality", "desc": "Nguy cơ tử vong ICU nhi", "status": "✅"},
        "PIM2": {"name": "PIM2 - Pediatric Index of Mortality 2", "desc": "Dự đoán tử vong ICU nhi (10 biến số)", "status": "✅"},
        "Pediatric SOFA": {"name": "Pediatric SOFA (pSOFA)", "desc": "Suy đa cơ quan ICU nhi - Điều chỉnh theo tuổi", "status": "✅"},
        "PECARN": {"name": "PECARN Pediatric Head Injury ⭐", "desc": "Dự đoán nhu cầu chụp CT đầu ở trẻ chấn thương đầu", "status": "✅"},
        "DHAKA Score": {"name": "DHAKA Score ⭐", "desc": "Phân loại mất nước ở trẻ em <5 tuổi bị tiêu chảy cấp", "status": "✅"},
    },
    
    "🤰 Sản khoa (Obstetrics)": {
        "Preeclampsia": {"name": "Preeclampsia Severity", "desc": "Mức độ nặng tiền sản giật (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Bishop Score": {"name": "Bishop Score", "desc": "Đánh giá cổ tử cung", "status": "✅"},
        "Modified Bishop": {"name": "Modified Bishop Score", "desc": "Dự đoán chuyển dạ", "status": "✅"},
    },
    
    "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)": {
        "CrCl": {"name": "CrCl - Cockcroft-Gault", "desc": "Độ thanh thải Creatinine - Điều chỉnh liều thuốc (DÙNG HÀNG NGÀY)", "status": "✅"},
        "BMI/IBW/BSA": {"name": "BMI | IBW | BSA", "desc": "Chỉ số cơ thể - BMI, Cân nặng lý tưởng, Diện tích da (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Osmolality": {"name": "Serum Osmolality & Gap", "desc": "Độ thẩm thấu - Nghi ngờ ngộ độc (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Anion Gap": {"name": "Anion Gap", "desc": "Khoảng trống anion - rối loạn acid-base", "status": "✅"},
        "Corrected Ca": {"name": "Corrected Calcium", "desc": "Canxi điều chỉnh theo albumin", "status": "✅"},
        "FENa": {"name": "FENa - Fractional Excretion of Sodium", "desc": "Phân biệt AKI tiền thận/thận", "status": "✅"},
        "HbA1c": {"name": "HbA1c - eAG Converter", "desc": "Chuyển đổi HbA1c sang đường huyết trung bình", "status": "✅"},
        "Winter Formula": {"name": "Winter Formula", "desc": "PCO2 dự đoán trong toan chuyển hóa", "status": "✅"},
        "Free T4 Index": {"name": "Free T4 Index (FTI)", "desc": "Chỉ số T4 tự do", "status": "✅"},
        "Osteoporosis DXA": {"name": "Đo loãng xương (DXA)", "desc": "Diễn giải T-score/Z-score, phân loại loãng xương, gợi ý điều trị", "status": "✅"},
        "FRAX": {"name": "Ước tính nguy cơ gãy xương (FRAX)", "desc": "Nhập kết quả FRAX 10 năm, so ngưỡng điều trị, khuyến nghị", "status": "✅"},
        "HOMA-IR": {"name": "HOMA-IR ⭐", "desc": "Đánh giá đề kháng insulin (DÙNG HÀNG NGÀY)", "status": "✅"},
        "FINDRISC": {"name": "FINDRISC ⭐", "desc": "Dự đoán nguy cơ đái tháo đường type 2 (DÙNG HÀNG NGÀY)", "status": "✅"},
        "MAP": {"name": "MAP - Mean Arterial Pressure", "desc": "Tính huyết áp trung bình động mạch (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Maintenance Fluids": {"name": "Maintenance Fluids Calculator", "desc": "Tính nhu cầu dịch duy trì hàng ngày (4-2-1 rule)", "status": "✅"},
        "Sodium Correction Hyperglycemia": {"name": "Sodium Correction for Hyperglycemia", "desc": "Điều chỉnh Na khi tăng đường huyết (Katz formula)", "status": "✅"},
        "Free Water Deficit": {"name": "Free Water Deficit in Hypernatremia", "desc": "Tính thiếu nước tự do trong tăng natri máu", "status": "✅"},
        "Weight-based Levothyroxine": {"name": "Weight-based Levothyroxine Dose Calculator ⭐", "desc": "Xác định liều levothyroxine dựa trên cân nặng để điều trị suy giáp nguyên phát ở người lớn", "status": "✅"},
    },
    
    "🦴 Thấp khớp - Miễn Dịch (Rheumatology/Immunology)": {
        "DAS28": {"name": "DAS28 - Disease Activity Score", "desc": "Hoạt động bệnh viêm khớp dạng thấp", "status": "✅"},
        "CDAI": {"name": "CDAI - Clinical Disease Activity Index", "desc": "Chỉ số hoạt động lâm sàng RA", "status": "✅"},
        "SDAI": {"name": "SDAI - Simplified Disease Activity Index", "desc": "Chỉ số đơn giản hóa RA", "status": "✅"},
        "ACR Criteria": {"name": "ACR/EULAR RA Classification", "desc": "Tiêu chuẩn chẩn đoán viêm khớp dạng thấp", "status": "✅"},
        "SLICC": {"name": "SLICC Criteria", "desc": "Tiêu chuẩn lupus ban đỏ hệ thống", "status": "✅"},
        "SLEDAI": {"name": "SLEDAI - SLE Disease Activity Index", "desc": "Hoạt động bệnh lupus", "status": "✅"},
        "Gout Diagnostic": {"name": "ACR/EULAR Gout Classification", "desc": "Chẩn đoán bệnh gout", "status": "✅"},
    },
    
    "🦠 Nhiễm khuẩn (Infectious Disease)": {
        "SIRS": {"name": "SIRS - Systemic Inflammatory Response", "desc": "Hội chứng đáp ứng viêm toàn thân", "status": "✅"},
        "Pitt Bacteremia": {"name": "Pitt Bacteremia Score", "desc": "Tiên lượng nhiễm khuẩn huyết", "status": "✅"},
        "MASCC": {"name": "MASCC Risk Index", "desc": "Nguy cơ sốt giảm bạch cầu hạt", "status": "✅"},
        "Centor": {"name": "Centor Score", "desc": "Viêm họng do liên cầu", "status": "✅"},
        "FeverPAIN": {"name": "FeverPAIN Score", "desc": "Viêm amidan - cần kháng sinh", "status": "✅"},
    },
    
    "🩹 Da liễu (Dermatology)": {
        "PASI": {"name": "PASI - Psoriasis Area Severity Index", "desc": "Mức độ nặng vẩy nến", "status": "✅"},
        "SCORAD": {"name": "SCORAD - SCORing Atopic Dermatitis", "desc": "Điểm viêm da cơ địa", "status": "✅"},
        "DLQI": {"name": "DLQI - Dermatology Life Quality Index", "desc": "Chất lượng cuộc sống bệnh da", "status": "✅"},
        "Burn TBSA": {"name": "TBSA - Total Body Surface Area", "desc": "Diện tích bỏng (quy tắc số 9)", "status": "✅"},
        "Parkland Formula": {"name": "Parkland Formula", "desc": "Truyền dịch ban đầu cho bỏng", "status": "✅"},
    },
    
    "🎗️ Ung thư (Oncology)": {
        "ECOG": {"name": "ECOG Performance Status", "desc": "Trạng thái thể trạng bệnh nhân ung thư", "status": "✅"},
        "Karnofsky": {"name": "Karnofsky Performance Scale", "desc": "Thang đo thể trạng", "status": "✅"},
        "Palliative Performance": {"name": "PPS - Palliative Performance Scale", "desc": "Thể trạng chăm sóc giảm nhẹ", "status": "✅"},
        "CIPN Grading": {"name": "CIPN Grading", "desc": "Phân độ tổn thương thần kinh ngoại biên", "status": "✅"},
        "MSKCC RCC Risk": {"name": "MSKCC Risk of Recurrence ⭐", "desc": "Dự đoán nguy cơ tái phát sau cắt thận ở ung thư thận (RCC)", "status": "✅"},
    },
    
    "🧠 Tâm thần - Tâm Lý (Psychiatry/Psychology)": {
        "PHQ-9": {"name": "PHQ-9 - Patient Health Questionnaire", "desc": "Sàng lọc trầm cảm", "status": "✅"},
        "GAD-7": {"name": "GAD-7 - Generalized Anxiety Disorder", "desc": "Rối loạn lo âu lan tỏa", "status": "✅"},
        "MMSE": {"name": "MMSE - Mini Mental State Exam", "desc": "Đánh giá nhận thức", "status": "✅"},
        "MoCA": {"name": "MoCA - Montreal Cognitive Assessment", "desc": "Đánh giá nhận thức Montreal", "status": "✅"},
        "CAM": {"name": "CAM - Confusion Assessment Method", "desc": "Đánh giá hôn mê lú lẫn", "status": "✅"},
        "CIWA-Ar": {"name": "CIWA-Ar", "desc": "Cai rượu - mức độ nặng", "status": "✅"},
        "COWS": {"name": "COWS - Clinical Opiate Withdrawal", "desc": "Cai opioid", "status": "✅"},
        "GMAWS": {"name": "GMAWS ⭐", "desc": "Đánh giá và theo dõi mức độ nặng của các triệu chứng cai rượu (AWS)", "status": "✅"},
    },
    
    "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)": {
        "ASA": {"name": "ASA Physical Status", "desc": "Phân loại nguy cơ phẫu thuật", "status": "✅"},
        "P-POSSUM": {"name": "P-POSSUM Score", "desc": "Nguy cơ tử vong phẫu thuật", "status": "✅"},
        "RCRI": {"name": "RCRI - Revised Cardiac Risk Index", "desc": "Nguy cơ tim mạch phẫu thuật", "status": "✅"},
        "Caprini": {"name": "Caprini VTE Risk Score", "desc": "Nguy cơ huyết khối sau phẫu thuật", "status": "✅"},
        "Aldrete Score": {"name": "Aldrete Score", "desc": "Hồi tỉnh sau gây mê", "status": "✅"},
        "Mallampati": {"name": "Mallampati Classification", "desc": "Đánh giá đường thở khó", "status": "✅"},
        "Apfel PONV": {"name": "Apfel PONV Risk Score", "desc": "Nguy cơ buồn nôn nôn sau mổ (PONV)", "status": "✅"},
        "Koivuranta PONV": {"name": "Koivuranta PONV Risk Score", "desc": "Nguy cơ PONV - Phiên bản mở rộng", "status": "✅"},
        "Wilson Risk": {"name": "Wilson Risk Score", "desc": "Dự đoán đặt nội khí quản khó", "status": "✅"},
        "El-Ganzouri": {"name": "El-Ganzouri Risk Index", "desc": "Đánh giá nguy cơ đặt nội khí quản khó", "status": "✅"},
        "LEMON": {"name": "LEMON Assessment", "desc": "Đánh giá đường thở khó (Look, Evaluate, Mallampati, Obstruction, Neck)", "status": "✅"},
        "Cormack-Lehane": {"name": "Cormack-Lehane Classification", "desc": "Phân loại tầm nhìn khi soi thanh quản", "status": "✅"},
        "Ramsay": {"name": "Ramsay Sedation Scale", "desc": "Đánh giá mức độ an thần", "status": "✅"},
        "RASS": {"name": "RASS - Richmond Agitation-Sedation Scale", "desc": "Đánh giá an thần/kích động (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Riker SAS": {"name": "Riker SAS - Sedation-Agitation Scale", "desc": "Thang điểm an thần/kích động", "status": "✅"},
        "PADSS": {"name": "PADSS - Post-Anesthesia Discharge Scoring System", "desc": "Tiêu chuẩn xuất viện sau gây mê ngoại trú", "status": "✅"},
        "ARISCAT": {"name": "ARISCAT - Assess Respiratory Risk in Surgical Patients", "desc": "Nguy cơ biến chứng hô hấp sau phẫu thuật", "status": "✅"},
        "CAM-ICU": {"name": "CAM-ICU - Confusion Assessment Method for ICU", "desc": "Chẩn đoán mê sảng trong ICU (DÙNG HÀNG NGÀY)", "status": "✅"},
        "4AT": {"name": "4AT - 4 A's Test for Delirium", "desc": "Sàng lọc mê sảng nhanh (2 phút)", "status": "✅"},
        "Surgical Apgar": {"name": "Surgical Apgar Score", "desc": "Đánh giá nguy cơ biến chứng sau mổ (3 yếu tố trong mổ)", "status": "✅"},
        "SORT": {"name": "SORT - Surgical Outcome Risk Tool", "desc": "Tiên lượng tử vong 30 ngày sau phẫu thuật không tim", "status": "✅"},
        "Gupta Cardiac": {"name": "Gupta Perioperative Cardiac Risk Index", "desc": "Nguy cơ tim mạch phẫu thuật (NSQIP-based)", "status": "✅"},
        "Goldman Cardiac": {"name": "Goldman Cardiac Risk Index", "desc": "Nguy cơ tim mạch phẫu thuật (Historical)", "status": "✅"},
        "Clavien-Dindo": {"name": "Clavien-Dindo Classification ⭐", "desc": "Phân loại biến chứng sau phẫu thuật (DÙNG HÀNG NGÀY)", "status": "✅"},
        "RHMP-30": {"name": "RHMP-30 ⭐", "desc": "Dự đoán nguy cơ tử vong 30 ngày sau phẫu thuật gãy xương hông", "status": "✅"},
        "WIFI Classification": {"name": "WIFI Classification ⭐", "desc": "Đánh giá mức độ nặng đe dọa chi ở bệnh nhân bệnh chi dưới", "status": "✅"},
        "Perioperative Anticoagulation": {"name": "Perioperative Anticoagulation Management ⭐⭐⭐", "desc": "Quản lý kháng đông trong phẫu thuật - Hướng dẫn ngừng và khởi động lại (MỚI, QUAN TRỌNG)", "status": "✅"},
    },
    
    "👁️ Mắt (Ophthalmology)": {
        "Intraocular Pressure": {"name": "IOP Correction", "desc": "Điều chỉnh nhãn áp theo CCT", "status": "✅"},
    },
    
    "😣 Đánh giá đau (Pain Assessment)": {
        "NRS": {"name": "NRS - Numeric Rating Scale", "desc": "Thang điểm số đánh giá đau (0-10) - DÙNG HÀNG NGÀY", "status": "✅"},
        "VAS": {"name": "VAS - Visual Analogue Scale", "desc": "Thang đo thị giác đánh giá đau (0-100mm)", "status": "✅"},
        "FLACC": {"name": "FLACC - Face, Legs, Activity, Cry, Consolability", "desc": "Đánh giá đau ở trẻ em (2 tháng - 7 tuổi)", "status": "✅"},
        "NIPS": {"name": "NIPS - Neonatal Infant Pain Scale", "desc": "Đánh giá đau ở trẻ sơ sinh (0-2 tháng)", "status": "✅"},
        "Wong-Baker": {"name": "Wong-Baker Faces Rating Scale", "desc": "Thang điểm khuôn mặt đánh giá đau (trẻ em và người lớn)", "status": "✅"},
        "DN4": {"name": "DN4 - Douleur Neuropathique 4", "desc": "Chẩn đoán đau thần kinh", "status": "✅"},
    },
    
    "🛏️ Chăm sóc điều dưỡng (Nursing Care)": {
        "Braden": {"name": "Braden Scale", "desc": "Đánh giá nguy cơ loét tì đè (DÙNG HÀNG NGÀY)", "status": "✅"},
        "Morse": {"name": "Morse Fall Scale", "desc": "Đánh giá nguy cơ té ngã (DÙNG HÀNG NGÀY)", "status": "✅"},
    },
    
    "👴 Lão khoa (Geriatrics)": {
        "CFS": {"name": "Clinical Frailty Scale (CFS) ⭐⭐⭐", "desc": "Đánh giá frailty (1-9) - Quan trọng cho tiên lượng và quyết định điều trị (MỚI)", "status": "✅"},
        "Morse Fall Scale": {"name": "Morse Fall Scale ⭐⭐⭐", "desc": "Đánh giá nguy cơ té ngã ở bệnh nhân nội trú (DÙNG HÀNG NGÀY) (MỚI)", "status": "✅"},
        "MMSE": {"name": "MMSE - Mini-Mental State Examination ⭐⭐⭐", "desc": "Screening cognitive impairment ở bệnh nhân cao tuổi (MỚI)", "status": "✅"},
        "MoCA": {"name": "MoCA - Montreal Cognitive Assessment ⭐⭐⭐", "desc": "Screening MCI và dementia - Nhạy hơn MMSE (MỚI)", "status": "✅"},
        "Beers Criteria": {"name": "Beers Criteria ⭐⭐⭐", "desc": "Potentially inappropriate medications in elderly - AGS Beers Criteria 2023 (MỚI)", "status": "✅"},
        "STOPP/START": {"name": "STOPP/START Criteria ⭐⭐⭐", "desc": "Screening Tool - Thuốc nên ngừng (STOPP) và thuốc nên bắt đầu (START) (MỚI)", "status": "✅"},
    },
}

