"""
Mapping between Articles/Protocols and Scores for bidirectional linking.

AUTO-GENERATED by scripts/auto_link_scores_to_content.py
DO NOT EDIT MANUALLY - Run the script to update
"""

from typing import Optional, Dict, List, Tuple
from scores.config import SCORES_BY_SPECIALTY


# Mapping: article_id -> list of score IDs
ARTICLE_TO_SCORES: Dict[str, List[Dict[str, str]]] = {
    "acid_suppression": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "acs_management": [
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HAS-BLED", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "GRACE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "acute_heart_failure": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "aki_kdigo": [
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "AKIN", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "RIFLE", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "FENa", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "anaphylaxis": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "antiallergy_medications": [
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "FENa", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "antibiotic_combinations": [
        {"score_id": "Corrected QT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "antibiotic_stewardship": [
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "ards-berlin-thong-khi-bao-ve-phoi-prone-peep-ecmo": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "ards_ventilation": [
        {"score_id": "RASS", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "atrial_fibrillation": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Corrected QT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HAS-BLED", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "benh-co-tim-phi-dai-hypertrophic-cardiomyopathy-hcm": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "benh-mach-vanh-man-chronic-coronary-syndrome": [
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "benh-van-tim-thuong-gap-aortic-mitral": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "beo-phi-nguoi-lon-danh-gia-va-dieu-tri": [
        {"score_id": "Gout Diagnostic", "specialty": "🦴 Thấp khớp - Miễn dịch (Rheumatology/Immunology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "bit-tieu-nhi-trai-laao-o-benh-nhan-rung-nhi": [
        {"score_id": "HAS-BLED", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "bronchodilators_copd_asthma": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "cap-cuu-noi-tiet-dka-hhs-bao-giap": [
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Anion Gap", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "cerebrovascular_medications": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "NIHSS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
    ],

    "chong-dong-rung-nhi-nvaf": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HAS-BLED", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "cirrhosis_complications": [
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Child-Pugh", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "co-truong-khang-tri-va-sbp": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Hunt & Hess", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
    ],

    "copd-benh-phoi-tac-nghen-man-tinh-gold": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
    ],

    "copd_asthma_exacerbation": [
        {"score_id": "Corrected QT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "dai-thao-duong-chan-doan-dieu-tri-quan-ly-ada-easd-2024": [
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "dai-thao-duong-typ-2-ngoai-tru-ada-2024": [
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "dot-quy-thieu-mau-nao-cap-ais": [
        {"score_id": "NIHSS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
    ],

    "electrolyte_disorders": [
        {"score_id": "Osmolality", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "FENa", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Anion Gap", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "gian-phe-quan-nguoi-lon-bronchiectasis": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
    ],

    "gout-chan-doan-va-dieu-tri-acr-eular": [
        {"score_id": "Gout Diagnostic", "specialty": "🦴 Thấp khớp - Miễn dịch (Rheumatology/Immunology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "AKIN", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "ha-natri-mau-cap-va-siad-h": [
        {"score_id": "Osmolality", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "hen-phe-quan-nguoi-lon-gina": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "ho-van-hai-la-nang-surgery-vs-teer-mitraclip": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "hoi-chung-buong-trung-da-nang-pcos": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "hoi-chung-mach-vanh-cap-acs-guideline": [
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "GRACE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "hoi-chung-suy-gan-cap-tren-nen-man-aclf": [
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SOFA-2 (2025)", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
    ],

    "hypertension": [
        {"score_id": "Gout Diagnostic", "specialty": "🦴 Thấp khớp - Miễn dịch (Rheumatology/Immunology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SCORE2-OP", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SCORE2", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "khang-huyet-khoi-sau-tavi-savr-va-van-nhan-tao": [
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
    ],

    "khong-chi-la-dapt-phoi-hop-oac-sau-pci-acs": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "lao-phoi-nguoi-lon-chan-doan-va-dieu-tri": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "loang-xuong-nguoi-lon-frax-va-dieu-tri": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "pain_relief_antiinflammatory": [
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Child-Pugh", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "FENa", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "pregnancy_hypertension_preeclampsia": [
        {"score_id": "Preeclampsia", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Modified Bishop", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Bishop Score", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Được đề cập trong bài viết"},
    ],

    "psychotropic_medications": [
        {"score_id": "Corrected QT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "quan-ly-duong-huyet-noi-tru-va-quanh-phau-thuat": [
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "roi-loan-calci-cap-tang-ha-calci-mau": [
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "roi-loan-lipid-nguy-co-rat-cao-mach-vanh": [
        {"score_id": "SCORE2-OP", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SCORE2", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "rung-nhi-chien-luoc-khang-dong-va-khoi-phuc-nhip": [
        {"score_id": "HAS-BLED", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "sepsis_bundle": [
        {"score_id": "SOFA-2 (2025)", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "qSOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SAPS II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "APACHE III", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SAPS III", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "stroke_management": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "NIHSS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ICH Score", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASPECTS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
    ],

    "suy-than-cap-va-man-o-nguoi-lon": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "suy-tim-cap-phan-loai-scai-va-xu-tri": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
    ],

    "suy-tim-ef-bao-ton-hfpef": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "suy-tim-hfref-4-tru-dieu-tri": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "t2dm_inpatient_outpatient": [
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
    ],

    "tang-ap-luc-tinh-mach-cua-va-gian-tinh-mach": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Hunt & Hess", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
    ],

    "tang-huyet-ap-cap-nhat-guideline": [
        {"score_id": "SCORE2-OP", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SCORE2", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "tang-huyet-ap-chan-doan-dieu-tri-esc-aha-2024": [
        {"score_id": "Gout Diagnostic", "specialty": "🦴 Thấp khớp - Miễn dịch (Rheumatology/Immunology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SCORE2-OP", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "SCORE2", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "thuyen-tac-phoi-cap-phan-tang-nguy-co-va-dieu-tri-esc": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PESI", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "tim-mach-o-benh-nhan-dai-thao-duong-typ-2": [
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "topical_medications": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "FENa", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "tran-dich-mang-phoi-va-viem-mu-mang-phoi": [
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-gan-virus-b-man-o-nguoi-lon": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "FENa", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-gan-virus-c-man-o-nguoi-lon": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-loet-da-day-ta-trang": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-mang-ngoai-tim-cap-acute-pericarditis": [
        {"score_id": "AKIN", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-noi-tam-mac-nhiem-khuan": [
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Hunt & Hess", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-phoi-benh-vien-hap-va-vap-ats-idsa": [
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Được đề cập trong bài viết"},
    ],

    "viem-phoi-cong-dong-cap-ats-idsa": [
        {"score_id": "CURB-65", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "xo-gan-con-bu-theo-doi-lau-dai": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
    ],

    "xo-gan-mat-bu": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
    ],

    "xuat-huyet-do-gian-tinh-mach-thuc-quan-da-day": [
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Được đề cập trong bài viết"},
    ],

    "xuat-huyet-nao-tu-phat-ich": [
        {"score_id": "ASA", "specialty": "🔪 Phẫu thuật & Gây mê (Surgery/Anesthesia)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "NIHSS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "ICH Score", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
    ],

    "xuat-huyet-tieu-hoa-tren-do-loet-khong-gian-tinh-mach": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Được đề cập trong bài viết"},
        {"score_id": "Rockall Score", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Được đề cập trong bài viết"},
    ],

}


# Mapping: protocol_function -> list of score IDs
PROTOCOL_TO_SCORES: Dict[str, List[Dict[str, str]]] = {
    "render_abdominal_trauma": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Đánh giá mức độ ý thức"},
    ],

    "render_acs": [
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "GRACE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "HEART Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CRUSADE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "PRECISE-DAPT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "DAPT Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_acute_appendicitis": [
        {"score_id": "Alvarado Score", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Liên quan đến protocol"},
        {"score_id": "4Ts Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Liên quan đến protocol"},
    ],

    "render_acute_decompensated_hf": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Killip", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_acute_gout": [
        {"score_id": "Gout Diagnostic", "specialty": "🦴 Thấp khớp - Miễn dịch (Rheumatology/Immunology)", "reason": "Liên quan đến protocol"},
    ],

    "render_acute_liver_failure": [
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Child-Pugh", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
    ],

    "render_acute_pancreatitis": [
        {"score_id": "BISAP", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Ranson", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
    ],

    "render_acute_respiratory_failure": [
        {"score_id": "ROX Index", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
    ],

    "render_adrenal_crisis": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Cần để chỉnh liều thuốc"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_aki": [
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "RIFLE", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "AKIN", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
    ],

    "render_anaphylaxis": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
    ],

    "render_aortic_dissection": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_ards": [
        {"score_id": "ARDS Berlin", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
    ],

    "render_asthma": [
        {"score_id": "ACT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
    ],

    "render_atrial_fibrillation": [
        {"score_id": "CHA2DS2-VASc", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "HAS-BLED", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Corrected QT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_cap": [
        {"score_id": "CURB-65", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "CRB-65 Score", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "PSI/PORT", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "SMART-COP", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
    ],

    "render_carbon_monoxide_poisoning": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để tính liều theo cân nặng"},
    ],

    "render_cardiac_arrest": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
    ],

    "render_cardiac_tamponade": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_chest_trauma": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Đánh giá mức độ ý thức"},
    ],

    "render_cirrhosis": [
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Child-Pugh", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
    ],

    "render_ckd": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_copd": [
        {"score_id": "BODE Index", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "mMRC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "CURB-65", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
    ],

    "render_decompensated_cirrhosis": [
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Child-Pugh", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
    ],

    "render_diabetic_nephropathy": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Cần để chỉnh liều thuốc"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_dic": [
        {"score_id": "Alvarado Score", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Liên quan đến protocol"},
        {"score_id": "4Ts Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Liên quan đến protocol"},
    ],

    "render_dka": [
        {"score_id": "Anion Gap", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
    ],

    "render_dvt_pe": [
        {"score_id": "Wells PE", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "PERC", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "PESI", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
        {"score_id": "Wells DVT", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Liên quan đến protocol"},
    ],

    "render_eclampsia": [
        {"score_id": "Preeclampsia", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Liên quan đến protocol"},
        {"score_id": "Bishop Score", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Liên quan đến protocol"},
        {"score_id": "Modified Bishop", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Liên quan đến protocol"},
    ],

    "render_emergency_dialysis": [
        {"score_id": "KDIGO", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_endocarditis": [
        {"score_id": "Duke", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_gi_bleeding": [
        {"score_id": "Glasgow-Blatchford", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Rockall Score", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "AIMS65", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
    ],

    "render_hap_vap": [
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "CURB-65", "specialty": "🫁 Hô hấp (Respiratory)", "reason": "Liên quan đến protocol"},
    ],

    "render_heat_stroke": [
        {"score_id": "NIHSS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ICH Score", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ASPECTS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ABCD2", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_hepatorenal_syndrome": [
        {"score_id": "MELD", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "MELD-Na", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Child-Pugh", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Cần để chỉnh liều thuốc"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_hf": [
        {"score_id": "NYHA", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Killip", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_hhs": [
        {"score_id": "Anion Gap", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
    ],

    "render_hypertensive_emergency": [
        {"score_id": "ASCVD Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "SCORE2", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "SCORE2-OP", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_hypertensive_nephrosclerosis": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Cần để chỉnh liều thuốc"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_hypoglycemia": [
        {"score_id": "HbA1c", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
    ],

    "render_intracranial_hypertension": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ICH Score", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_lower_gi_bleeding": [
        {"score_id": "Glasgow-Blatchford", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Rockall Score", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
        {"score_id": "AIMS65", "specialty": "🩸 Tiêu hóa - Gan Mật (GI/Hepatology)", "reason": "Liên quan đến protocol"},
    ],

    "render_meningitis": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_nephrolithiasis": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Cần để chỉnh liều thuốc"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_nephrotic_syndrome": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Cần để chỉnh liều thuốc"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

    "render_nstemi": [
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "GRACE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Killip", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "HEART Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CRUSADE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_opioid_overdose": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để tính liều theo cân nặng"},
    ],

    "render_organophosphate_poisoning": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để tính liều theo cân nặng"},
    ],

    "render_paracetamol_overdose": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để tính liều theo cân nặng"},
    ],

    "render_preeclampsia": [
        {"score_id": "Preeclampsia", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Liên quan đến protocol"},
        {"score_id": "Bishop Score", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Liên quan đến protocol"},
        {"score_id": "Modified Bishop", "specialty": "🤰 Sản khoa (Obstetrics)", "reason": "Liên quan đến protocol"},
    ],

    "render_salicylate_overdose": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để tính liều theo cân nặng"},
    ],

    "render_sepsis": [
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "qSOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "SAPS II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "SAPS III", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE III", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE IV", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "Lactate Clearance", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_sepsis_3hour": [
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "qSOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "SAPS II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "SAPS III", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE III", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE IV", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "Lactate Clearance", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Liên quan đến protocol"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_shock": [
        {"score_id": "SOFA", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "Lactate Clearance", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
        {"score_id": "APACHE II", "specialty": "🚨 Cấp cứu & Hồi sức (Emergency & Critical Care)", "reason": "Liên quan đến protocol"},
    ],

    "render_status_epilepticus": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_stemi": [
        {"score_id": "TIMI Risk", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "GRACE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Killip", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "HEART Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CRUSADE Score", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_stroke": [
        {"score_id": "NIHSS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "mRS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ICH Score", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ASPECTS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "ABCD2", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_thyrotoxic_crisis": [
        {"score_id": "Corrected QT", "specialty": "❤️ Tim mạch (Cardiology)", "reason": "Liên quan đến protocol"},
    ],

    "render_toxic_alcohol_poisoning": [
        {"score_id": "BMI/IBW/BSA", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để tính liều theo cân nặng"},
    ],

    "render_transfusion": [
        {"score_id": "DIC Score", "specialty": "🩺 Huyết học & Đông máu (Hematology)", "reason": "Liên quan đến protocol"},
    ],

    "render_traumatic_brain_injury": [
        {"score_id": "GCS", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
        {"score_id": "Canadian CT Head", "specialty": "🧠 Thần kinh (Neurology)", "reason": "Liên quan đến protocol"},
    ],

    "render_uti_pyelonephritis": [
        {"score_id": "eGFR", "specialty": "🧪 Thận - Điện giải (Nephrology)", "reason": "Liên quan đến protocol"},
        {"score_id": "CrCl", "specialty": "💉 Nội tiết - Chuyển hóa (Endocrinology/Metabolism)", "reason": "Cần để chỉnh liều thuốc"},
    ],

}


def get_scores_for_article(article_id: str) -> List[Dict[str, str]]:
    """Get list of scores for a given article ID."""
    return ARTICLE_TO_SCORES.get(article_id, [])


def get_scores_for_protocol(protocol_function: str) -> List[Dict[str, str]]:
    """Get list of scores for a given protocol function."""
    return PROTOCOL_TO_SCORES.get(protocol_function, [])


def get_score_info(score_id: str, specialty: str) -> Optional[Dict[str, str]]:
    """Get score information from SCORES_BY_SPECIALTY."""
    specialty_scores = SCORES_BY_SPECIALTY.get(specialty, {})
    return specialty_scores.get(score_id)


def has_scores(article_id: str = None, protocol_function: str = None) -> bool:
    """Check if an article or protocol has associated scores."""
    if article_id:
        return article_id in ARTICLE_TO_SCORES and len(ARTICLE_TO_SCORES[article_id]) > 0
    if protocol_function:
        return protocol_function in PROTOCOL_TO_SCORES and len(PROTOCOL_TO_SCORES[protocol_function]) > 0
    return False