"""
Expanded Drug Interactions Database
Organized by drug classes for better maintainability
"""

from .anticoagulants import ANTICOAGULANT_INTERACTIONS
from .antibiotics import ANTIBIOTIC_INTERACTIONS
from .cardiovascular import CARDIOVASCULAR_INTERACTIONS
from .antidiabetics import ANTIDIABETIC_INTERACTIONS
from .psychiatry import PSYCHIATRY_INTERACTIONS
from .gi import GI_INTERACTIONS
from .other import OTHER_INTERACTIONS
from .analgesics import ANALGESICS_INTERACTIONS
from .antifungals_antivirals import ANTIFUNGALS_ANTIVIRALS_INTERACTIONS
from .immunosuppressants_oncology import IMMUNOSUPPRESSANTS_ONCOLOGY_INTERACTIONS

# Combine all interactions
EXPANDED_INTERACTIONS = {
    **ANTICOAGULANT_INTERACTIONS,
    **ANTIBIOTIC_INTERACTIONS,
    **CARDIOVASCULAR_INTERACTIONS,
    **ANTIDIABETIC_INTERACTIONS,
    **PSYCHIATRY_INTERACTIONS,
    **GI_INTERACTIONS,
    **OTHER_INTERACTIONS,
    **ANALGESICS_INTERACTIONS,
    **ANTIFUNGALS_ANTIVIRALS_INTERACTIONS,
    **IMMUNOSUPPRESSANTS_ONCOLOGY_INTERACTIONS,
}

__all__ = [
    'EXPANDED_INTERACTIONS',
    'ANTICOAGULANT_INTERACTIONS',
    'ANTIBIOTIC_INTERACTIONS',
    'CARDIOVASCULAR_INTERACTIONS',
    'ANTIDIABETIC_INTERACTIONS',
    'PSYCHIATRY_INTERACTIONS',
    'GI_INTERACTIONS',
    'OTHER_INTERACTIONS',
    'ANALGESICS_INTERACTIONS',
    'ANTIFUNGALS_ANTIVIRALS_INTERACTIONS',
    'IMMUNOSUPPRESSANTS_ONCOLOGY_INTERACTIONS',
]
