"""
Collaboration / Share Settings
Export / Import user state (favorites, saved searches, etc.)
"""

import json
import streamlit as st

from utils.page_helper import setup_page, render_standard_footer
from utils.analytics_events import track_page_view, track_feature_usage

from components.collaboration import export_state_payload, import_state_payload, payload_to_json_bytes


setup_page(
    page_title="Collaboration",
    page_icon="🤝",
    description="Export / Import favorites và cấu hình người dùng",
    mobile_header=True,
)

track_page_view("Collaboration")
track_feature_usage("collaboration_page_open")

st.title("🤝 Collaboration (Export / Import)")
st.caption("Chia sẻ cấu hình cá nhân (favorites, saved searches...) qua file JSON. Dữ liệu lưu cục bộ, không gửi lên server.")

tab_export, tab_import = st.tabs(["⬇️ Export", "⬆️ Import"])

with tab_export:
    st.markdown("### ⬇️ Export user state")
    st.info("Tải xuống file JSON để chuyển sang máy khác hoặc chia sẻ với đồng nghiệp.")

    payload = export_state_payload(extra={"note": "Generated by Clinical Assistant"})
    st.json(payload, expanded=False)

    st.download_button(
        label="⬇️ Tải file user-state.json",
        data=payload_to_json_bytes(payload),
        file_name="user-state.json",
        mime="application/json",
        use_container_width=True,
        on_click=lambda: track_feature_usage("collab_export_state"),
    )

with tab_import:
    st.markdown("### ⬆️ Import user state")
    st.warning("Import sẽ cập nhật session hiện tại. Bạn có thể chọn Merge hoặc Replace.")

    mode = st.radio("Chế độ import:", options=["merge", "replace"], horizontal=True)

    uploaded = st.file_uploader("Chọn file JSON đã export", type=["json"])
    if uploaded is not None:
        try:
            raw = uploaded.read().decode("utf-8")
            payload = json.loads(raw)
        except Exception as e:
            st.error(f"Không đọc được JSON: {e}")
            payload = None

        if payload:
            ok, msg = import_state_payload(payload, mode=mode)
            if ok:
                st.success(msg)
                track_feature_usage(f"collab_import_state_{mode}")
                if st.button("🔄 Reload", type="primary"):
                    st.rerun()
            else:
                st.error(msg)

render_standard_footer()

