[theme]
primaryColor = "#00897B"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E0F2F1"
textColor = "#263238"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[runner]
magicEnabled = false
